// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBIEsrDf2VkTB9cUkrNB1yFSLH84Wxs7M',
    appId: '1:420360314638:web:519fec7e8b67c26c36815f',
    messagingSenderId: '420360314638',
    projectId: 'olmeg-connect',
    authDomain: 'olmeg-connect.firebaseapp.com',
    storageBucket: 'olmeg-connect.firebasestorage.app',
    measurementId: 'G-WQKGKH1XMV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcmlsJdqhvbXMZ9kuL2KuhmDWcdFaas5k',
    appId: '1:420360314638:android:82bde37cc6d42a9336815f',
    messagingSenderId: '420360314638',
    projectId: 'olmeg-connect',
    storageBucket: 'olmeg-connect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJZbG_Ucifofx-2djN15EHUoUvzKcXUXc',
    appId: '1:420360314638:ios:ab136c20bcc7e92836815f',
    messagingSenderId: '420360314638',
    projectId: 'olmeg-connect',
    storageBucket: 'olmeg-connect.firebasestorage.app',
    iosBundleId: 'com.example.olmegConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJZbG_Ucifofx-2djN15EHUoUvzKcXUXc',
    appId: '1:420360314638:ios:ab136c20bcc7e92836815f',
    messagingSenderId: '420360314638',
    projectId: 'olmeg-connect',
    storageBucket: 'olmeg-connect.firebasestorage.app',
    iosBundleId: 'com.example.olmegConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBIEsrDf2VkTB9cUkrNB1yFSLH84Wxs7M',
    appId: '1:420360314638:web:400500045760988c36815f',
    messagingSenderId: '420360314638',
    projectId: 'olmeg-connect',
    authDomain: 'olmeg-connect.firebaseapp.com',
    storageBucket: 'olmeg-connect.firebasestorage.app',
    measurementId: 'G-0V4F3QJT9D',
  );

}